### ISSUE TITLE
How to get whistlist of an user?

### ISSUE THREAD

**Issue by IRediTOTO** [imranhsayed/headless-cms#25]
Hi I saw your video about add whistlist. But how can query it if we know user ID? 
I am not familiar with PHP so i can custom. Thank you

**Comment by imranhsayed** [comment]
@IRediTOTO 
You need to make a login query using https://github.com/wp-graphql/wp-graphql-jwt-authentication, then pass the 
JWT in authorization header when making the get wishlist query request, it will automatically know, the user details since user JWT is passed in the headers.
The query wont work just with user id, without JWT because its user's private information.
Notice what happens in amazon, if you want to add a product to wishlist or view, you need to login.

**Comment by IRediTOTO** [comment]
@imranhsayed  Thank you for your answer. 
I got idea how to login, but I can't find how to query it. Can you make a sort syntax here ? :\
